### PR TITLE
refactor: change cy-data attributes to data-cy

### LINKED ISSUE #41: Change cy-data attributes to data-cy

### PR DESCRIPTION
**Pull request by pmareke**
Fixes #41

### CODE REVIEW

**Comment by pmareke** [comment]
Thanks to you for your time! It's always a great time to learn something new! I'd love to keep helping!

**Comment by d3lm** [comment]
Sure thing! I am always there if you have a specific question. Contributing to open source is a great opportunity to learn something new.

**Comment by d3lm** [comment]
One tiny nit-pick here. Maybe you can remove the commit body as this is already indicated by your changes. You can keep `Fixes...` tho. I usually use the body to explain the big picture if it's more complex but this PR is pretty straight forward and the commit message already indicates what this does.

Once done, I ll merge it 😊

**Comment by pmareke** [comment]
Done!

Thanks again for everything!

**Comment by pmareke** [comment]
Sorry but I don't know how to do that...I'll search about it and try!

**Comment by pmareke** [comment]
I think now it's finally done, I amend the commit and then push again.

**Comment by d3lm** [comment]
No problem. This requires a little bit of git. The first step is to enter a the interactive rebase mode and take your last commit:

`git rebase --interactive HEAD~1`

Then you can enter the _insert_ mode by pressing `i`. Change `pick` to `r` for "reword". Then press `ESC` to exit the insert mode. Now write and quick with `:wq` which will open up the commit message. Enter the insert mode again and remove the text expect `Fixes...`. When you are done editing the commit message, exit the insert mode again and write quit the file.

After that you have successfully changed the commit message and have rewritten the history from your commit onwards. No big deal. Now you can force push into your PR branch:

`git push -f fork my-feature-branch`

Let me know if that worked or if you need further assistance.

**Comment by d3lm** [comment]
Sweet. Yep, amending also works. Maybe a little more straight forward than an interactive rebase 😂I am just so used to do interactive rebases lol.

Anyhow, good job!

**Comment by d3lm** [comment]
This has landed 👍

**Comment by pmareke** [comment]
I prefer your solution too ahahah, I'm going to reading and practicing again because it's git quite important to understand! Keep in contact.

**Pull request merged**
