### PR TITLE
feat: upgrade cypress

### PR DESCRIPTION
**Pull request by d3lm**
This PR updates cypress to 3.1. Test parallelization is not available in the free plan.

### CODE REVIEW

**Comment by d3lm** [comment]
PR reopened to re-trigger Travis.

**Comment by d3lm** [comment]
Closing this PR because Travis isn't in the mood to pick up changes.

**Comment by timdeschryver** [comment]
Did you get it working again, it seems like your `.travis.yml` isn't formatted correctly?

**Comment by d3lm** [comment]
Yep, got it working. That's what I have noticed after half an hour. I didn't check the `Request` page on Travis 😅 Thanks for asking tho!

**Pull request closed without merging**
